// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAChwLwFwXX8Qxo4p6O63uUv0N8JKd7CXg',
    appId: '1:88731306678:web:c1f2583329e69f53d3f417',
    messagingSenderId: '88731306678',
    projectId: 'fir-login-demo-94e1b',
    authDomain: 'fir-login-demo-94e1b.firebaseapp.com',
    storageBucket: 'fir-login-demo-94e1b.firebasestorage.app',
    measurementId: 'G-5MR34SPYVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2meG2pwllKMBlT7tc7O_SwqaCUdcTxTA',
    appId: '1:88731306678:android:9da497b22c07ed53d3f417',
    messagingSenderId: '88731306678',
    projectId: 'fir-login-demo-94e1b',
    storageBucket: 'fir-login-demo-94e1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrIlcgpioIeyEcZx3eJ7B4naF0DFuRbg',
    appId: '1:88731306678:ios:4fcc4fd85a1576abd3f417',
    messagingSenderId: '88731306678',
    projectId: 'fir-login-demo-94e1b',
    storageBucket: 'fir-login-demo-94e1b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrIlcgpioIeyEcZx3eJ7B4naF0DFuRbg',
    appId: '1:88731306678:ios:4fcc4fd85a1576abd3f417',
    messagingSenderId: '88731306678',
    projectId: 'fir-login-demo-94e1b',
    storageBucket: 'fir-login-demo-94e1b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAChwLwFwXX8Qxo4p6O63uUv0N8JKd7CXg',
    appId: '1:88731306678:web:d5bd90ca7f004e84d3f417',
    messagingSenderId: '88731306678',
    projectId: 'fir-login-demo-94e1b',
    authDomain: 'fir-login-demo-94e1b.firebaseapp.com',
    storageBucket: 'fir-login-demo-94e1b.firebasestorage.app',
    measurementId: 'G-7BKE1CR776',
  );
}
