import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import '../firebase_options.dart'; // generated by `flutterfire configure`
import 'login.dart';

Future<void> main() async {
  // Needed before calling any Firebase function.
  WidgetsFlutterBinding.ensureInitialized();

  // Start up Firebase using the config for this project.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Auth Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.cyan),
      ),
      // App always starts on the Login screen.
      home: const LoginScreen(),
    );
  }
}
